### ISSUE TITLE
Im Multi-Modus keine Auswahlmöglichkeit für Attribute Lat und Lng

### ISSUE THREAD

**Issue by design23** [MetaModels/filter_perimetersearch#13]
Hi,

hab filter_perimetersearch 2.0.0.alpha installiert. Filter existiert dann auch, allerdings kann ich im Multimodus keine Attribute auswählen.
![bildschirmfoto 2017-03-03 um 14 32 41](https://cloud.githubusercontent.com/assets/6112308/23552869/4b2583d2-001e-11e7-873f-69b4e090bcf6.png)

**Comment by discordier** [comment]
@stefanheimes could you take care of this? It is your baby after all. :smile_cat:

**Comment by stefanheimes** [comment]
Found it. It was a bug in the filter_text, see: https://github.com/MetaModels/filter_text/commit/550da1df49781b2be504af1ca1a6c97662157c4b

With the version 2.0.1 from the filter_text, everything should be a-okay.

**Comment by patrickschroer** [comment]
Hatte das selbe Problem, funktioniert jetzt einwandfrei.

**Comment by zonky2** [comment]
thx
