### ISSUE TITLE
Port this to Contao 4 and MM 2.1

### ISSUE THREAD

**Issue by MacKP** [MetaModels/filter_perimetersearch#18]
Wäre super, wenn das auch für Contao 4 fertig gemacht werden würde.
Ich brauche das leider relativ dringend. Kannst dich gerne bei mir melden ;-)

Viele Grüße

**Comment by stefanheimes** [comment]
I have a new version for you. Can u test it please. The Backend and Forntend is working for me. If possible try it first on a test system. On any Problems call me or add it here to the ticket.

**Comment by stefanheimes** [comment]
Open work:
- [ ] Check PHPDoc headers
- [ ] Run tests
- [ ] Waiting for okay from MacKP

**Comment by richardhj** [comment]
There are some entries in the deprecated-autoload.php missing.
And: I've been using the namespace `FilterRule` (for filter_fromto etc.) while you have chosen the namespace `FilterRules`. We should decide for one at the MM-call.

**Comment by discordier** [comment]
We have decided to use singular Namespaces everywhere.

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@MacKP could you please have a final look at this and tell if your issue has been resolved?

**Comment by zonky2** [comment]
@MacKP pls check current version

**Comment by zonky2** [comment]
works at "P2"
