### ISSUE TITLE
Leere Ausgabe bei Contao 3.2.9 und Nutzung von Perimetersearch

### ISSUE THREAD

**Issue by liquid-a** [MetaModels/filter_perimetersearch#2]
Ich nutze Contao 3.2.9. Die MetaModels Version kann ich auf den ersten Blick nirgends im Backend finden - Download und Installation erfolgten am 15.4.! Die Version der Perimeter Search entspricht der aktuellen (von Jan.).

Die Installation von MetalModels funktioniert auch, ich kann Adressdatensätze nach Land und PLZ filtern. Die Datensätze haben einen Wert Längen- und Breitengrad (decimal).Diese Werte sind in der Perimetersearch eingerichtet (Screenshot anbei).
![screenshot_perimeter_search](https://cloud.githubusercontent.com/assets/7712553/3090512/9e776338-e58d-11e3-840a-ee9deac39edd.png)

Sobald ich die Perimetersearch zum Filter hinzufüge (aktiviere) wird die Webseite weiß, also ohne Inhalte und ohne Fehlermeldung (Firebug meldet in der Konsole 500 Internal Server Error). Aktiviere ich im Filter nur die Perimetersearch und lasse den Auswahlfilter für das Land und die PLZ deaktiviert, erscheint die Liste mit den Adressen (also keine leere Webseite) aber kein Perimetersearchfilter.

Das Log-File gibt folgende Werte aus:

```
[27-May-2014 11:37:10 Europe/Berlin] 
PHP Deprecated notice: Usage of deprecated /projekt/system/modules/metamodels/deprecated/TableMetaModelFilterSetting.php in /projekt/system/modules/metamodels/deprecated/TableMetaModelFilterSetting.php on line 17
#0 [internal function]: __error(16384, 'Usage of deprec...', '/kunden/426192_...', 17, Array)
#1 /projekt/system/modules/metamodels/deprecated/TableMetaModelFilterSetting.php(17): trigger_error('Usage of deprec...', 16384)
#2 /projekt/system/modules/core/library/Contao/ClassLoader.php(152): include('/kunden/426192_...')
#3 [internal function]: Contao\ClassLoader::load('TableMetaModelF...')
#4 [internal function]: spl_autoload_call('TableMetaModelF...')
#5 /projekt/system/modules/metamodels/MetaModels/Dca/Filter.php(623): get_class_methods('TableMetaModelF...')
#6 /projekt/system/modules/generalDriver/DcGeneral/Callbacks/ContaoStyleCallbacks.php(117): MetaModels\Dca\Filter->drawSetting(Array, 'perimetersearch', Object(DC_General), Array)
#7 /projekt/system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(2264): DcGeneral\Callbacks\ContaoStyleCallbacks->labelCallback(Object(DcGeneral\Data\DefaultModel), 'perimetersearch', Array)
#8 /projekt/system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(2289): DcGeneral\Controller\DefaultController->buildLabel(Object(DcGeneral\Data\DefaultModel))
#9 /projekt/system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(2178): DcGeneral\Controller\DefaultController->treeWalkModel(Object(DcGeneral\Data\DefaultModel), 0, Array, Array)
#10 /projekt/system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(1364): DcGeneral\Controller\DefaultController->treeViewM5()
#11 /projekt/system/modules/generalDriver/DcGeneral/DC_General.php(2382): DcGeneral\Controller\DefaultController->showAll()
#12 /projekt/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(176): DcGeneral\DC_General->showAll()
#13 /projekt/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(196): MetaModels\BackendIntegration\Module->runDC()
#14 /projekt/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(210): MetaModels\BackendIntegration\Module->performNormal()
#15 /projekt/system/modules/core/classes/Backend.php(272): MetaModels\BackendIntegration\Module->generate()
#16 /projekt/contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#17 /projekt/contao/main.php(293): Main->run()
#18 {main}
```

**Comment by stefanheimes** [comment]
There is an update for the TNG, can you test it, please.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@liquid-a could you please have a final look at this and tell if your issue has been resolved?
