### ISSUE TITLE
fix deprecations

### ISSUE THREAD

**Issue by zonky2** [MetaModels/filter_perimetersearch#24]
fix deprecations...

**Comment by discordier** [comment]
See comment https://github.com/MetaModels/filter_perimetersearch/commit/277b42ae3571154e2c416ded37995c8829a5c736#r32198696
@stefanheimes please evaluate.

**Comment by baumannsven** [comment]
Fixed in 2b8c18c35081b5fb530f88ab4d418860e7be9a67
