### ISSUE TITLE
blank option nicht mehr dabei?

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/filter_perimetersearch#29]
Moin,
durch ein Update einer Contao 3 Version in Kombi mit MM + perimetersearch fiel mir gerade auf, dass keine leere Option mehr zur Verfügung steht. Im Backend Formular des Filters konnte man da ja eh nicht einstellen aber es war vorher in der Klasse Perimetersearch in der Methode getRangeWidget vorhanden.

Also: 'includeBlankOption' => true,

Version ist: 2.1.2

**Comment by zonky2** [comment]
die Option ist hier raus geflogen https://github.com/MetaModels/filter_perimetersearch/commit/08dc63cae00b74caff1f0cbc1f37477de5fe4a44#diff-93fe114143d5f56e72ff997a1f1a0c7c - warum, kann ich ad hoc auch nicht sagen...
@baumannsven warum ist das raus?

**Comment by zonky2** [comment]
Habe mir das nochmal angesehen - wenn man schon vom Freitextfeld auf eine definierte Liste umstellt, muss da auch was ausgewählt werden.. wenn blankOptiopn wieder rein kommen würde, müsste man dan mandatory auf true setzen...

solange die Meisten damit leben können, schließe ich das Ticket
