### ISSUE TITLE
Zwei Filter auf einer Seite - Fatal error

### ISSUE THREAD

**Issue by Dockmedia** [MetaModels/filter_perimetersearch#3]
Hallo,

ich habe gerade meine erste Website mit Metamodels umgesetzt und bin sehr beeindruckt was das Metamodelsteam hier auf die Beine gestellt hat. VIelen Dank dafür.

So nun zu meinem Problem:

Ich habe einen Seite (Maschinensuche) auf der ein Filter eingebunden ist und darunter eine Liste, die die Ergebnisse ausgibt. Soweit funktioniert alles.
Dann habe ich eine Seite mit einer Umkreissuche, die mir die Ergebnisse der Umkreissuche ausgibt. Soweit ist noch alles okay. 
Die Umkreissuche ist in jedem Header der Seite eingebunden. Wenn ich jetzt die Seite mit der Maschinensuche aufrufe bekomme ich folgenden Fehler:

Fatal error: Declaration of MetaModelFilterSettingPerimetersearch::prepareRules() must be compatible with MetaModels\Filter\Setting\ISimple::prepareRules(MetaModels\Filter\IFilter $objFilter, $arrFilterUrl) in /.../.../.../.../.../system/modules/metamodelsfilter_perimetersearch/MetaModelFilterSettingPerimetersearch.php on line 460

Wenn ich den Filter Umkreissuche aus dem Header entferne läuft die Seite wieder.

Zum System:

Contao 3.2.9

Metamodels
metamodels/core 	dev-contao3 @ ccc32f 	2014-05-08 13:19:32 	LGPL-3.0+

filter_perimetersearch für Contao 3

Ohne Composer

Ich hoffe Ihr könnt das ungefähr nachvollziehen was ich meine.
Ich freue mich über jede Hilfe.

Grüße Marco

**Comment by xantippe** [comment]
@beyerph ist das noch aktuell?

**Comment by beyerph** [comment]
Nicht mehr aktuell, danke :-)
