### ISSUE TITLE
FR: Rückgabe um Entfernung erweitern

### ISSUE THREAD

**Issue by zonky2** [MetaModels/filter_perimetersearch#5]
mit der folgenden Umstellung sollte es möglich sein, zur Item-ID auch die Entfernung mit zurück zu geben

```
$strSelect = "SELECT item_id, round(sqrt( power(2 * pi() / 360 * ($lat - latitude) * 6371,2) + power(2 * pi() / 360 * ($lng - longitude) * 6371 * COS( 2 * pi() / 360 * ($lat + latitude) * 0.5 ),2))) AS item_dist"
. "FROM tl_metamodel_geolocation "
. "WHERE item_dist <= $intDist "
. "AND att_id=? "
. "ORDER BY item_dist";  
```
zumal die Rechnung dann auch nur 1x durchgeführt werden muss

siehe auch https://community.contao.org/de/showthread.php?42275-Umkreissuche-in-MetaModels&p=340357&viewfull=1#post340357

**Comment by xantippe** [comment]
Nachtrag: noch was kommt hinzu: beim Filter werden immer nur die "IDs" der Items weiter geheben - solange es (noch) keine "virtuellen Attribute" gibt, wird das nicht/kaum gehen

**Comment by bastlwastl** [comment]
Ich würde gerne diese Anpassung in Auftrag geben!
Habe diesbezüglich schon dreimal eine Anfrage an MetaModels geschrieben - leider nie eine Antwort bekommen.
An wen muss ich mich da am besten wenden?

Gruß
Bastian

**Comment by zonky2** [comment]
Hallo Bastian,
upps... wo hast Du die Anfrage geschrieben? eigentlich werden die Anfragen im "MM-Team" zügig kommuniziert...

**Comment by bastlwastl** [comment]
Ich habe meine Anfrage zweimal über das Formular auf der Seite "Support erhalten" und einmal als direkte eMail an die auf der Kontakt-Seite aufgeführte Adresse gesendet.

Sollte sich jemand für meine Anfrage interessieren - bitte melden.
Ich denke das wäre eine Sache, die bei der Umkreissuche nicht fehlen sollte!

Gruß
Bastian

**Comment by stefanheimes** [comment]
This issue is obsolete since we have the geodistance attribute. So i will close this issue now. If you have any trouble with the distance between a point and the searched address, please use the https://github.com/MetaModels/attribute_geodistance attribute.

Thanks.
