### ISSUE TITLE
Fehler nach Installation

### ISSUE THREAD

**Issue by bastlwastl** [MetaModels/filter_perimetersearch#6]
Neuinstallation Contao 3.2.16
Aktuelle MetaModels nightly-tng 

Nach der Installation werden folgende Fehlermeldungen ausgegeben:
<pre>
<code>Warning: Illegal offset type in system/modules/metamodels/classes/src/MetaModels/Filter/Setting/AbstractFilterSettingTypeFactory.php on line 240
#0 system/modules/metamodels/classes/src/MetaModels/Filter/Setting/AbstractFilterSettingTypeFactory.php(240): __error(2, 'Illegal offset ...', 'sy...', 240, Array)
#1 system/modules/metamodels/classes/src/MetaModels/Filter/Setting/Events/LegacyListener.php(62): MetaModels\Filter\Setting\AbstractFilterSettingTypeFactory->addKnownAttributeType(Array)
#2 system/modules/metamodels/config/event_listeners.php(85): MetaModels\Filter\Setting\Events\LegacyListener::registerLegacyFactories(Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent))
#3 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent), 'metamodels.filt...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent), 'metamodels.filt...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.filt...', Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent))
#6 system/modules/metamodels/classes/src/MetaModels/Filter/Setting/FilterSettingFactory.php(59): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.filt...', Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent))
#7 system/modules/metamodels/classes/src/MetaModels/MetaModelsServiceContainer.php(143): MetaModels\Filter\Setting\FilterSettingFactory->setServiceContainer(Object(MetaModels\MetaModelsServiceContainer))
#8 system/modules/metamodels/config/services.php(90): MetaModels\MetaModelsServiceContainer->setFilterFactory(Object(MetaModels\Filter\Setting\FilterSettingFactory))
#9 system/modules/metamodels/config/services.php(107): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
#10 system/modules/pimple-pimple/classes/lib/Pimple.php(126): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
#11 system/modules/pimple-pimple/classes/lib/Pimple.php(83): Pimple::{closure}(Object(Pimple))
#12 system/modules/metamodels/classes/src/MetaModels/Helper/SubSystemBoot.php(93): Pimple->offsetGet('metamodels-serv...')
#13 system/cache/config/config.php(1730): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#14 [internal function]: Contao\Config->{closure}(Object(Pimple))
#15 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(84): call_user_func(Object(Closure), Object(Pimple))
#16 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(328): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#17 system/initialize.php(233): DependencyInjection\Container\ContainerInitializer->init()
#18 contao/main.php(24): require_once('sy...')
#19 {main}
</code>
</pre>

<pre>
<code>
Warning: Illegal offset type in system/modules/metamodels/classes/src/MetaModels/Filter/Setting/AbstractFilterSettingTypeFactory.php on line 240
#0 system/modules/metamodels/classes/src/MetaModels/Filter/Setting/AbstractFilterSettingTypeFactory.php(240): __error(2, 'Illegal offset ...', 'sy...', 240, Array)
#1 system/modules/metamodels/classes/src/MetaModels/Filter/Setting/Events/LegacyListener.php(62): MetaModels\Filter\Setting\AbstractFilterSettingTypeFactory->addKnownAttributeType(Array)
#2 system/modules/metamodels/config/event_listeners.php(85): MetaModels\Filter\Setting\Events\LegacyListener::registerLegacyFactories(Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent))
#3 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent), 'metamodels.filt...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent), 'metamodels.filt...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.filt...', Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent))
#6 system/modules/metamodels/classes/src/MetaModels/Filter/Setting/FilterSettingFactory.php(59): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.filt...', Object(MetaModels\Filter\Setting\Events\CreateFilterSettingFactoryEvent))
#7 system/modules/metamodels/classes/src/MetaModels/MetaModelsServiceContainer.php(143): MetaModels\Filter\Setting\FilterSettingFactory->setServiceContainer(Object(MetaModels\MetaModelsServiceContainer))
#8 system/modules/metamodels/config/services.php(90): MetaModels\MetaModelsServiceContainer->setFilterFactory(Object(MetaModels\Filter\Setting\FilterSettingFactory))
#9 system/modules/metamodels/config/services.php(107): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
#10 system/modules/pimple-pimple/classes/lib/Pimple.php(126): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
#11 system/modules/pimple-pimple/classes/lib/Pimple.php(83): Pimple::{closure}(Object(Pimple))
#12 system/modules/metamodels/classes/src/MetaModels/Helper/SubSystemBoot.php(93): Pimple->offsetGet('metamodels-serv...')
#13 system/cache/config/config.php(1730): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#14 [internal function]: Contao\Config->{closure}(Object(Pimple))
#15 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(84): call_user_func(Object(Closure), Object(Pimple))
#16 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(328): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#17 system/initialize.php(233): DependencyInjection\Container\ContainerInitializer->init()
#18 contao/main.php(24): require_once('sy...')
#19 {main}
</code>
</pre>

<pre>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /html/contao/system/helper/functions.php:70) in system/modules/core/library/Contao/System.php on line 484
#0 [internal function]: __error(2, 'Cannot modify h...', 'sy...', 484, Array)
#1 system/modules/core/library/Contao/System.php(484): setcookie('BE_USER_AUTH', '00a2f472255e680...', 1418932563, '/', '', false, true)
#2 system/modules/core/library/Contao/User.php(215): Contao\System::setCookie('BE_USER_AUTH', '00a2f472255e680...', 1418932563, NULL, NULL, false, true)
#3 system/modules/core/classes/BackendUser.php(180): Contao\User->authenticate()
#4 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/ViewCombinations.php(52): Contao\BackendUser->authenticate()
#5 system/modules/metamodels/classes/src/MetaModels/Helper/ViewCombinations.php(132): MetaModels\BackendIntegration\ViewCombinations->authenticateUser()
#6 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/ViewCombinations.php(52): MetaModels\Helper\ViewCombinations->getUser()
#7 system/modules/metamodels/classes/src/MetaModels/Helper/ViewCombinations.php(112): MetaModels\BackendIntegration\ViewCombinations->authenticateUser()
#8 system/modules/metamodels/classes/src/MetaModels/Helper/ViewCombinations.php(145): MetaModels\Helper\ViewCombinations->calculateCacheKey()
#9 system/modules/metamodels/classes/src/MetaModels/Helper/ViewCombinations.php(95): MetaModels\Helper\ViewCombinations->loadFromCache()
#10 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Boot.php(110): MetaModels\Helper\ViewCombinations->__construct(Object(MetaModels\MetaModelsServiceContainer), Object(Contao\BackendUser))
#11 system/modules/metamodels/config/event_listeners.php(61): MetaModels\BackendIntegration\Boot->perform(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#15 system/modules/metamodels/classes/src/MetaModels/Helper/SubSystemBoot.php(128): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#16 system/cache/config/config.php(1730): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#17 [internal function]: Contao\Config->{closure}(Object(Pimple))
#18 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(84): call_user_func(Object(Closure), Object(Pimple))
#19 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(328): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#20 system/initialize.php(233): DependencyInjection\Container\ContainerInitializer->init()
#21 contao/main.php(24): require_once('sy...')
#22 {main}
</code>
</pre>

<pre>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /html/contao/system/helper/functions.php:70) in system/modules/core/library/Contao/System.php on line 484
#0 [internal function]: __error(2, 'Cannot modify h...', 'sy...', 484, Array)
#1 system/modules/core/library/Contao/System.php(484): setcookie('BE_USER_AUTH', '00a2f472255e680...', 1418932563, '/', '', false, true)
#2 system/modules/core/library/Contao/User.php(215): Contao\System::setCookie('BE_USER_AUTH', '00a2f472255e680...', 1418932563, NULL, NULL, false, true)
#3 system/modules/core/classes/BackendUser.php(180): Contao\User->authenticate()
#4 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/ViewCombinations.php(52): Contao\BackendUser->authenticate()
#5 system/modules/metamodels/classes/src/MetaModels/Helper/ViewCombinations.php(112): MetaModels\BackendIntegration\ViewCombinations->authenticateUser()
#6 system/modules/metamodels/classes/src/MetaModels/Helper/ViewCombinations.php(145): MetaModels\Helper\ViewCombinations->calculateCacheKey()
#7 system/modules/metamodels/classes/src/MetaModels/Helper/ViewCombinations.php(95): MetaModels\Helper\ViewCombinations->loadFromCache()
#8 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Boot.php(110): MetaModels\Helper\ViewCombinations->__construct(Object(MetaModels\MetaModelsServiceContainer), Object(Contao\BackendUser))
#9 system/modules/metamodels/config/event_listeners.php(61): MetaModels\BackendIntegration\Boot->perform(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#13 system/modules/metamodels/classes/src/MetaModels/Helper/SubSystemBoot.php(128): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#14 system/cache/config/config.php(1730): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#15 [internal function]: Contao\Config->{closure}(Object(Pimple))
#16 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(84): call_user_func(Object(Closure), Object(Pimple))
#17 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(328): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#18 system/initialize.php(233): DependencyInjection\Container\ContainerInitializer->init()
#19 contao/main.php(24): require_once('sy...')
#20 {main}
</code>
</pre>

<pre>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /html/contao/system/helper/functions.php:70) in system/modules/core/library/Contao/System.php on line 484
#0 [internal function]: __error(2, 'Cannot modify h...', 'sy...', 484, Array)
#1 system/modules/core/library/Contao/System.php(484): setcookie('BE_USER_AUTH', '00a2f472255e680...', 1418932563, '/', '', false, true)
#2 system/modules/core/library/Contao/User.php(215): Contao\System::setCookie('BE_USER_AUTH', '00a2f472255e680...', 1418932563, NULL, NULL, false, true)
#3 system/modules/core/classes/BackendUser.php(180): Contao\User->authenticate()
#4 contao/main.php(59): Contao\BackendUser->authenticate()
#5 contao/main.php(292): Main->__construct()
#6 {main}
</code>
</pre>

<pre>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /html/contao/system/helper/functions.php:70) in system/modules/core/library/Contao/Template.php on line 298
#0 [internal function]: __error(2, 'Cannot modify h...', 'sy...', 298, Array)
#1 system/modules/core/library/Contao/Template.php(298): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(162): Contao\Template->output()
#3 contao/main.php(284): Contao\BackendTemplate->output()
#4 contao/main.php(146): Main->output()
#5 contao/main.php(293): Main->run()
#6 {main}
</code>
</pre>

<pre>
<code>
Warning: Cannot modify header information - headers already sent by (output started at /html/contao/system/helper/functions.php:70) in system/modules/core/library/Contao/Template.php on line 299
#0 [internal function]: __error(2, 'Cannot modify h...', 'sy...', 299, Array)
#1 system/modules/core/library/Contao/Template.php(299): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(162): Contao\Template->output()
#3 contao/main.php(284): Contao\BackendTemplate->output()
#4 contao/main.php(146): Main->output()
#5 contao/main.php(293): Main->run()
#6 {main}
</code>
</pre>

Gruß Bastian

**Comment by stefanheimes** [comment]
There is a update for the tng branch. Now it is possible to load the flter via composer.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@bastlwastl could you please have a final look at this and tell if your issue has been resolved?

**Comment by bastlwastl** [comment]
Habe versucht zu testen.
Composer gibt leider folgende Fehlemeldung aus:
<pre>
<code>
Loading composer repositories with package information
Installing dependencies
  - Installing contao-community-alliance/composer-plugin (2.3.3)
    Loading from cache
    <warning>Failed to download contao-community-alliance/composer-plugin from dist: RecursiveDirectoryIterator::__construct(/html/contao/composer/vendor/contao-community-alliance/composer-plugin): failed to open dir: No such file or directory</warning>
    <warning>Now trying to download from source</warning>
  - Installing contao-community-alliance/composer-plugin (2.3.3)
    Cloning 0af8ad67c9c584adda04cf5643ade7c38056c2c4
</code></pre>

**Comment by stefanheimes** [comment]
Okay. 

Ich glaube das ist kein Fehler sondern mehr ein Information. Zudem hat es etwas mit dem composer-plugin zu tun und nicht mit dem peri search. Sieht so aus als würde der Ordner fehlen.

**Comment by bastlwastl** [comment]
Ja, das scheint eine Information zu sein.
Darüber wird folgende Meldung ausgegeben.
<pre>
<code> 
RecursiveDirectoryIterator::__construct(/composer/vendor/contao-community-alliance/composer-plugin): failed to open dir: No such file or directory
 </code>
</pre>

Bei mir fehlt das composer-plugin.
Irgendwie kann ich das nicht installieren.

Ich benötige mommentan den peri search nicht.
Würde aber trotzdem gerne testen und Feedback geben können.
Ich setz mich morgen nochmal dran....
