### ISSUE TITLE
Kein Eintrag im gewünschten Umkreis

### ISSUE THREAD

**Issue by jonas1616** [MetaModels/filter_perimetersearch#7]
Wenn kein Eintrag im gewünschten Umkreis gefunden wird werden einfach alle vorhanden Einträge angezeigt.

MM: dev-tng (85826a73)
Perimetersearch: dev-tng (7e51abc0)

**Comment by stefanheimes** [comment]
Fixed with 6e8b7853c8d9636eae25fd21e2c48a5ed12bcbf8 in Version 2.0.0-alpha2

**Comment by xantippe** [comment]
kann m.E. geschlossen werden

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@jonas1616 could you please have a final look at this and tell if your issue has been resolved?
