### ISSUE TITLE
Bugs in Filtereinstellungen (TNG, C 3.5.2)

### ISSUE THREAD

**Issue by xantippe** [MetaModels/filter_perimetersearch#9]
Beim Erstellen eines Filters sind aktuell folgende Fehler vorhanden:

* bei "Single Mode" ist die Auswahl des Attributes leer (bis auf den Strich); "Multi Mode" geht
* bei dem Lookup-Service gibt es keine Auswahl (bis auf den Strich) - beim Speichern erscheint eine Fehlermeldung, dass die Einstellung fehlt (ist aber nicht als Pflichtfeld markiert)

Gruss

Version: 07cb3412

**Comment by xantippe** [comment]
1.Pkt hat sich geklärt - man benötigt ein spezielles Attribut "geolocation" dafür - das ist aktuell aber (noch) nicht per Composer verfügbar

**Comment by xantippe** [comment]
mit dem Hotfix https://github.com/MetaModels/filter_perimetersearch/tree/hotfix-events kann der Lookup-Service wieder aufgerufen werden - es kommt aber ein neuer Bug...

für die "TwoSimpleAtt"-Suche wurden Lat und Long in zwei Attribute verteilt und in den Filtereinstellungen die entsprechenden Attribute ausgewählt - gibt am im FE z.B. die PLZ ein kommt folgende Fehlermeldung

```
PHP Fatal error:  Call to a member function get() on null in /web/composer/vendor/metamodels/filter_perimetersearch/src/MetaModels/Filter/Setting/Perimetersearch.php on line 433  
```

siehe https://github.com/MetaModels/filter_perimetersearch/blob/hotfix-events/src/MetaModels/Filter/Setting/Perimetersearch.php#L433

das Attribut ```single_attr_id``` existiert hier nicht und könne ein "C&P-Fehler" aus Zeile 386 sein 

ich würde sagen, Zeile 433 muss so aussehen
```            ->execute($intDist);
```

**Comment by stefanheimes** [comment]
Fixed with 6e8b7853c8d9636eae25fd21e2c48a5ed12bcbf8 in Version 2.0.0-alpha2

**Comment by stefanheimes** [comment]
By the way, thanks for the fix and PR @xantippe

**Comment by xantippe** [comment]
Danke auch!
http://metamodels.readthedocs.org/de/latest/manual/extended/perimetersearch.html
